/** Norwegian bokmål overrides for better-auth-ui (admin + sign-in). */
export const authUiLocalization = {
  errors: {
    generic: "Noe gikk galt",
    invalidCredentials: "Feil brukernavn eller passord",
    invalidCode: "Ugyldig kode",
    sessionExpired: "Økten er utløpt. Logg inn på nytt.",
    permissionDenied: "Du har ikke tilgang",
    rateLimited: "For mange forsøk. Vent litt og prøv igjen.",
    passwordTooShort: "Passordet er for kort",
    passwordTooLong: "Passordet er for langt",
    accountExists: "Kontoen finnes allerede",
  },
  auth: {
    account: "Konto",
    alreadyHaveAnAccount: "Har du allerede en konto?",
    confirmPassword: "Bekreft passord",
    confirmPasswordPlaceholder: "Bekreft passordet",
    email: "E-post",
    emailPlaceholder: "navn@innsjekk.local",
    fieldRequired: "Dette feltet er påkrevd",
    forgotPassword: "Glemt passord",
    forgotPasswordLink: "Glemt passord?",
    hidePassword: "Skjul passord",
    invalidEmail: "Ugyldig e-postadresse",
    name: "Navn",
    namePlaceholder: "Navn",
    needToCreateAnAccount: "Trenger du en konto?",
    newPassword: "Nytt passord",
    newPasswordPlaceholder: "Nytt passord",
    or: "eller",
    password: "Passord",
    passwordPlaceholder: "passord",
    rememberMe: "Husk meg",
    showPassword: "Vis passord",
    signIn: "Logg inn",
    signOut: "Logg ut",
    signUp: "Opprett konto",
    tooLong: "Maks {{max}} tegn",
    tooShort: "Minst {{min}} tegn",
  },
  settings: {
    settings: "Innstillinger",
  },
}

export const adminUiLocalization = {
  accessDenied: "Ingen tilgang",
  accessDeniedDescription: "Du har ikke tillatelse til å administrere brukere.",
  active: "Aktiv",
  accountInformation: "Konto",
  admin: "Administrator",
  banned: "Utestengt",
  banDuration: "Varighet (dager)",
  banDurationDescription: "La stå tomt for permanent utestengelse.",
  banExpires: "Utestengelse utløper",
  banReason: "Årsak",
  banUser: "Utesteng",
  cancel: "Avbryt",
  close: "Lukk",
  copyUserId: "Kopier ID",
  created: "Opprettet",
  createUser: "Ny bruker",
  deleteUser: "Slett",
  dangerZone: "Fareområde",
  email: "E-post",
  emailVerified: "E-post bekreftet",
  endsWith: "Slutter med",
  filterAllStatuses: "Alle",
  loadUsersError: "Kunne ikke hente brukere",
  loadUsersErrorDescription: "Prøv igjen.",
  name: "Navn",
  moreActions: "Flere handlinger",
  noUsers: "Ingen brukere",
  noUsersDescription: "Endre søket, eller opprett en bruker.",
  nextPage: "Neste side",
  previousPage: "Forrige side",
  impersonateUser: "Etterlign",
  overview: "Profil",
  password: "Passord",
  profileAndAccess: "Bruker",
  retry: "Prøv igjen",
  role: "Rolle",
  search: "Søk",
  searchOperator: "Søkemodus",
  searchContains: "Inneholder",
  startsWith: "Starter med",
  searchByEmail: "Søk etter e-post",
  searchByName: "Søk etter brukernavn",
  sessions: "Sesjoner",
  noSessions: "Ingen aktive sesjoner",
  revoke: "Avslutt",
  revokeAllSessions: "Avslutt alle sesjoner",
  saveRole: "Lagre rolle",
  saveChanges: "Lagre",
  saveUser: "Lagre",
  setPassword: "Sett passord",
  security: "Sikkerhet",
  status: "Status",
  sort: "Sorter",
  sortNewest: "Nyeste først",
  sortOldest: "Eldste først",
  sortNameAscending: "A–Å",
  sortNameDescending: "Å–A",
  stopImpersonating: "Stopp etterligning",
  userDetails: "Bruker",
  userId: "ID",
  unknownView: "Ukjent visning",
  unknownViewDescription: "Denne admin-visningen finnes ikke:",
  unbanUser: "Opphev utestengelse",
  users: "Brukere",
  usersDescription: "Administratorer for innsjekk.",
  usersPaginationRange: "{{from}}–{{to}} av {{total}}",
}
